#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Официальный сайт: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# Russian translation made by Vadimus#3081 and github.com/Quantum-0 <3

# Do not change this setting
file-version: 5

Messages:
  Title:
    # Сообщение отправляется перед входом в систему
    before-login:
      title: "&a&lДобро пожаловать!"
      subtitle: "&7Использование: /login <пароль>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Сообщение отправляется перед регистрацией
    before-register:
      title: "&a&lДобро пожаловать!"
      subtitle: "&7Использование: /register <пароль> <повтор пароля>"
      delays:
        start: 0
        duration: 9999
        end: 6
    # Сообщение отправляется после успешного входа в систему
    after-login:
      title: ""
      subtitle: "&aВы успешно зашли!"
      delays:
        start: 0
        duration: 60
        end: 6
    # Сообщение отправляется после успешной регистрации
    after-register:
      title: ""
      subtitle: "&aВы успешно зарегистрировались!"
      delays:
        start: 0
        duration: 60
        end: 6

  delay-kick:
    # Сообщение отправляется, когда игрок слишком долго регистрируется
    register-kick: "&cВремя регистрации истекло."

    # Сообщение отправляется, когда игрок слишком долго входит в аккаунт
    login-kick: "&cВы слишком долго входили в аккаунт."

  successful-operations:
    # Сообщение отправляется, когда игрок меняет свой пароль
    password-changed: "&aВаш пароль был успешно изменён."

    # Сообщение отправляется, когда игрок успешно входит в аккаунт
    successful-login: "&aВы успешно вошли в аккаунт."

    # Сообщение отправляется, когда игрок успешно регистрируется
    successful-register: "&aВы успешно зарегистрировались."

    # Сообщение отправляется, когда игрок удаляет свой аккаунт
    unregister-kick: "&cРегистрация аккаунта успешно отозвана."

  kick-messages:
    # Сообщение отправляется, когда игрок пытается зайти на сервер с маленькой разницей в нике
    nick-already-registered: "&cВы не можете войти с ником {0}&r\n&r&cЭто имя пользователя уже зарегистрировано как {1}&r\n&r\n&r&cДля входа вы должны использовать свой никнейм без прописых/строчных букв"

    # Сообщение отправляется, когда игрок слишком много раз вводит неправильный пароль
    failed-many-times: "&cВы слишком много раз ввели неправильный пароль."

    # Сообщение отправляется, когда игрок вводит неправильный пароль
    incorrect-password: "&cНеправильный пароль! Попытайтесь снова."

  error-messages:
    # Сообщение отправлено, когда вы уже вошли в систему.
    already-login: "&cВы уже авторизованы."

    # Сообщение отправляется, когда ник уже зарегистрирован.
    already-registered: "&cДанное имя пользователя уже зарегистрировано."

    # Сообщение отправляется, когда ник еще не зарегистрирован.
    not-registered: "&cЭтот ник еще не зарегистрирован."

    # Сообщение отправляется, когда первый пароль не соответствует второму паролю
    passwords-dont-match: "&cПароли не совпадают."

    # Сообщение отправляется, когда игрок пытается сменить пароль, вводя тот же пароль, что и текущий
    password-same-as-old: "&cВведённый пароль совпадает с текущим."

    # Сообщение отправляется, когда игрок вводит слишком длинный пароль
    password-too-large: "&cВы ввели слишком длинный пароль."

    # Сообщение отправляется, когда игрок вводит слишком короткий пароль
    password-too-small: "&cВы ввели слишком короткий пароль."

    # Сообщение отправляется, когда у игрока недостаточно прав для использования какой-либо команды
    insufficient-permissions: "&cУ вас нет прав для использования этой команды."

    # Сообщение выводится, когда игрока кикает из-за того, что он уже зашёл на сервер
    already-online: "&cЭтот игрок уже зашёл на сервер."

    # Сообщение отправляется, если эту команду нельзя выполнить в консоли
    player-command-usage: "&cЭту команду нельзя использовать в консоли."

    # Сообщение отправляется после перезагрузки плагина
    plugin-reload-message: "&eOpenLogin успешно перезагружен."

    # Сообщение отправляется, если операция с базой данных не была успешно выполнена
    database-error: "&cК сожалению, нам не удалось выполнить эту операцию. Пожалуйста, попробуйте еще раз. [SQL FAIL]"

  other-messages:
    # Сообщение для использования команды /login
    message-login: "&eВведите: &7/login <пароль>&e."

    # Сообщения для использования команды /register
    message-register: "&eВведите: &7/register <пароль> <повтор пароля>&e."

    # Сообщение для команды смены пароля /changepassword
    message-changepassword: "&eВведите: &7/changepassword <текущий пароль> <новый пароль>&e."

    # Сообщение отправлено для использования команды /unregister
    message-unregister: "&eИспользуйте команду &7/unregister <текущий пароль>&e."
